# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-24 04:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0007_auto_20180424_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetables',
            name='date_t',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
    ]
