# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-30 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0009_auto_20180424_1036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timetables',
        ),
    ]
